produtos:
  produtoA:
    name: "Produto A"
    description: "Standard candy box."
    config: { Blue: 1, Green: 3, Red: 1 }
  produtoB:
    name: "Produto B"
    description: "A different mix of candies."
    config: { Blue: 2, Green: 4, Red: 2 }
  produtoC:
    name: "Produto C"
    description: "Another variation of candy mix."
    config: { Blue: 2, Green: 1, Red: 3 }
  produtoD:
    name: "Produto D"
    description: "Includes a special red candy addition."
    config: { Blue: 2, Green: 2, Red: 4 }
  produtoE:
    name: "Produto E"
    description: "A unique blend of candies."
    config: { Blue: 3, Green: 2, Red: 1 }
  produtoF:
    name: "Produto F"
    description: "A special edition candy box."
    config: { Blue: 2, Green: 2, Red: 2 }
  produtoG:
    name: "Produto G"
    description: "A limited edition candy box."
    config: { Blue: 3, Green: 3 }
  produtoH:
    name: "Produto H"
    description: "A seasonal candy box."
    config: { Blue: 3 }
  produtoI:
    name: "Produto I"
    description: "A classic candy box."
    config: { Red: 5 , Green: 1 } 